# Generated by Django 5.1.1 on 2024-09-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pond', '0002_alter_pond_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond',
            name='image_name',
            field=models.CharField(max_length=255),
        ),
    ]
