# Generated by Django 5.1.2 on 2024-10-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sampling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsampling',
            name='food_quantity',
            field=models.IntegerField(),
        ),
    ]
