# Generated by Django 5.1.2 on 2024-11-07 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sampling', '0003_alter_foodsampling_food_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsampling',
            name='sample_date',
        ),
        migrations.AddField(
            model_name='foodsampling',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
