# Generated by Django 5.1.1 on 2024-11-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='status',
        ),
    ]
