# Generated by Django 5.1.1 on 2024-10-08 16:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
        ('pond', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='ending_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='cycle',
            old_name='cycle_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cycle',
            old_name='starting_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='cycle',
            old_name='owner',
            new_name='supervisor',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='fish_amounts',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='pond',
        ),
        migrations.CreateModel(
            name='CycleFishDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fish_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.cycle')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pond.pond')),
            ],
        ),
    ]
