# Generated by Django 5.1.1 on 2024-10-10 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_rename_ending_date_cycle_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclefishdistribution',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_fish_amount', to='cycle.cycle'),
        ),
    ]
