# Generated by Django 5.1.2 on 2024-11-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_remove_cycle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
