# Generated by Django 5.1.1 on 2024-10-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0003_alter_cyclefishdistribution_cycle'),
        ('pond', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CycleFishDistribution',
            new_name='PondFishAmount',
        ),
    ]
