<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-11-28 15:43
=======
# Generated by Django 5.1.3 on 2024-12-04 17:41
>>>>>>> staging

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('cycle', '0001_initial'),
=======
        ('cycle', '0003_cycle_is_stopped'),
        ('pond', '0001_initial'),
>>>>>>> staging
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('POND_QUALITY', 'POND_QUALITY'), ('FISH_SAMPLING', 'FISH_SAMPLING'), ('FOOD_SAMPLING', 'FOOD_SAMPLING')], max_length=20)),
                ('day_of_culture', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['day_of_culture'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('POND_QUALITY', 'POND_QUALITY'), ('FISH_SAMPLING', 'FISH_SAMPLING'), ('FOOD_SAMPLING', 'FOOD_SAMPLING')], max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('DONE', 'DONE')], default='TODO', max_length=4)),
                ('assignee', models.CharField(blank=True, max_length=13)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.cycle')),
                ('pond', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pond.pond')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
