# Generated by Django 5.1.1 on 2024-10-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
