# Generated by Django 5.1.1 on 2024-10-02 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pond_quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondquality',
            name='ammonia',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pondquality',
            name='dissolved_oxygen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pondquality',
            name='nitrate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pondquality',
            name='orp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pondquality',
            name='ph_level',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)]),
        ),
        migrations.AlterField(
            model_name='pondquality',
            name='phosphate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pondquality',
            name='salinity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pondquality',
            name='water_circulation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pondquality',
            name='water_clarity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pondquality',
            name='water_temperature',
            field=models.FloatField(),
        ),
    ]
