# Generated by Django 5.1.2 on 2024-10-20 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0004_rename_cyclefishdistribution_pondfishamount'),
        ('fish_sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishsampling',
            name='cycle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cycle.cycle'),
            preserve_default=False,
        ),
    ]
