# Generated by Django 5.1.1 on 2024-09-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_sampling', '0001_initial'),
        ('pond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishsampling',
            name='pond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pond.pond'),
        ),
        migrations.DeleteModel(
            name='Pond',
        ),
    ]
